[package]
name = "toolkit-ctf"
version = "0.1.0"
edition = "2021"


[dependencies]
base64 = "0.22.0"
num-bigint = "0.4.4"
rand = "0.8.5"

[[bin]]
name = "base16"
path = "examples/base16.rs"

[[bin]]
name = "primality"
path = "examples/primality.rs"
